# Configuration for an OpenFAAS function. Deploy like this:
# > faas-cli secret create zoomtoics-keys --from-file=.env
# > faas-cli publish -f stack.yml --platforms linux/arm/v7,linux/amd64
# > faas-cli deploy -f stack.yml

version: 1.0
provider:
  name: openfaas
functions:
  zoomtoics:
    lang: python3
    handler: ./zoomtoics
    image: ${DOCKER_USER:-jasonprado}/zoomtoics:latest
    annotations:
      topic: cron-function
      schedule: "@hourly"
    secrets:
      - zoomtoics-keys
